# Generated by Django 5.2.1 on 2025-05-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='score',
            new_name='memoryscore',
        ),
    ]
