# Generated by Django 5.2.1 on 2025-05-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_score_memory_memoryscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='username',
            new_name='profilename',
        ),
    ]
