# Generated by Django 5.2.1 on 2025-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_username_memory_profilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='memoryproof',
            field=models.CharField(default=None),
        ),
    ]
