# Generated by Django 5.2.1 on 2025-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_memory_memoryproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memoryproof',
            field=models.CharField(),
        ),
    ]
