# Generated by Django 5.2.1 on 2025-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_memory_memoryproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memoryproof',
            field=models.ImageField(upload_to='memoryproofs/'),
        ),
    ]
