# Generated by Django 5.2.1 on 2025-05-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
