# Generated by Django 5.2.1 on 2025-05-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorygame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(upload_to='')),
                ('profilename', models.CharField()),
                ('memoryscore', models.IntegerField()),
                ('memoryproof', models.ImageField(upload_to='memoryproofs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
