# Generated by Django 5.2.1 on 2025-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_memorygame_delete_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memoryproof',
            field=models.ImageField(null=True, upload_to='memoryproofs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='memoryscore',
            field=models.IntegerField(default=0),
        ),
    ]
