# Generated by Django 5.2.1 on 2025-05-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_memoryproof_user_memoryscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brickproof',
            field=models.ImageField(null=True, upload_to='brickproofs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='brickscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='guessproof',
            field=models.ImageField(null=True, upload_to='guessproofs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='guessscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='stoneproof',
            field=models.ImageField(null=True, upload_to='stoneproofs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='stonescore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='waterproof',
            field=models.ImageField(null=True, upload_to='waterproofs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='waterscore',
            field=models.IntegerField(default=0),
        ),
    ]
