# Generated by Django 5.2.1 on 2025-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_user_brickproof_alter_user_guessproof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brickproof',
            field=models.ImageField(default='defaults/defaultprofileimage.jpeg', upload_to='brickproofs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='guessproof',
            field=models.ImageField(default='defaults/defaultprofileimage.jpeg', upload_to='guessproofs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='memoryproof',
            field=models.ImageField(default='defaults/defaultprofileimage.jpeg', upload_to='memoryproofs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(blank=True, default='defaults/defaultprofileimage.jpeg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stoneproof',
            field=models.ImageField(default='defaults/defaultprofileimage.jpeg', upload_to='stoneproofs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='waterproof',
            field=models.ImageField(default='defaults/defaultprofileimage.jpeg', upload_to='waterproofs/'),
        ),
    ]
